jsconf/2018.jsconf.eu

config.json
https://github.com/hail2u/node-css-mqpacker
=> add sorting to mqpacker-plugin

contents/css/_typography.css
- put in more margin on top of h2, less margin under h2
- therefor i decreased the margin-bottom on h1
- fixed letter-spacing for h2
- made h2 inline-block, so that border-bottom only grows with longest text-line
- adjusted h2 small screen the same way
=> styling h2, margins h1 and h2

contents/copy/imprint/imprint.md, contents/imprint.json, templates/pages/imprint.html.njk, templates/partials/footer.html.njk
We need a imprint - because of legal
=> feat(imprint): imprint is needed

contents/css/_links.css
=> new hover-effect for .link--underline

contents/css/_layout.css, contents/css/_links.css, contents/css/_topbar.css, contents/css/_typography.css, contents/css/_vars-breakpoints.css
=> Fix topbar layout

.travis.yml
For details see https://docs.travis-ci.com/user/caching/
=> Speed up Travis by caching NPM modules.

contents/css/_layout.css, contents/css/_topbar.css, contents/css/_typography.css, package-lock.json, package.json, plugins/nunjucks.js, plugins/postcss.js, templates/layouts/default.html.njk
Reverts jsconf/2018.jsconf.eu#72
Apparently our website is down.
=> Revert "Convert URLs to static assets into immutable URLs"

templates/pages/index.html.njk, templates/partials/topbar.html.njk
Fixes #79.
TODO: 
https://2018.jsconf.eu/call-for-speakers
=> Remove Call for Speakers

contents/css/_speaker.css, templates/pages/speakers.html.njk, templates/partials/topbar.html.njk
Not ideal, but looks good enough to me to announce some speakers.
=> Make speakers page launchable.

contents/news/speaker-announcements.md, templates/pages/index.html.njk, templates/pages/news.html.njk
I noticed along the way that we need to date sort these, but don't have the time right now.
=> News post for speaker announcement

contents/css/_links.css, contents/news/speaker-announcements.md, templates/pages/news.html.njk
Small tweak to text in news post.
=> Link all of news overview text and clean up CSS a bit.

contents/sw.js
This should make the schedule available when the conf WIFI is offline.
=> Use cache documents if the network doesn't respond within 1s.

plugins/svg.js, templates/layouts/default.html.njk
It is 242KB (wow) pre-gzip. Definitely too big to be inlined.
=> ⛹Load sprite externally

.travis.yml
See https://github.com/travis-ci/travis-ci/issues/9312#issuecomment-371590249 for details.
=> Fix GH Pages deployment

contents/js/main.js, contents/manifest-json.txt, templates/layouts/default.html.njk
`manifest.json` doesn't work because json files are special in wintersmith.
=> Make touchstart listener passive and manifest loadable.

contents/copy/why/why.md, contents/news/why-you-should-attend.md, contents/why.json, templates/pages/about.html.njk, templates/pages/why.html.njk
All content imported from 2017.
=> Create the why page

.travis.yml, locals-generated.json, package.json, plugins/nunjucks.js, scripts/generate-locals.js, templates/layouts/default.html.njk
Too much time on my hands on this 16h flight :)
=> Automatically update the typekit preloads.

templates/layouts/default.html.njk
And only preload the fonts where woff2 is supported.
=> Avoid credentialed connection for TypeKit

.travis.yml, package-lock.json, package.json, redirects.json, scripts/generate-redirects.js, templates/pages/redirect.html.njk
Just add an entry to `redirect.json` to redirect from any HTML file to a new one.
=> Add mechanism for easy addition of redirects into system.

scripts/spreadsheet-import/index.js
Due to a bug I introduced when refactoring the spreadsheet-import tool, we were not downloading images for our MCs and team members. This PR fixes this issue.
=> Fix import script to include MCs & teams images

.travis.yml, templates/filters/sortObjects.js, tests/post-build.js
To prevent we don't unpublish all speakers by accident again.
CC @janl
=> Super basic post build test to make sure we don't break the site.

contents/copy/speakers/guide.md, contents/speakers-guide.json, templates/pages/speakers-guide.html.njk
=> Add skeleton for the Speakers & MCs Guide page

scripts/purify-css.js, third_party/purify-css/LICENCE, third_party/purify-css/README.local.md, third_party/purify-css/purify-css.js
This increases reduction of CSS from 60 to 83%. The default purify-css is conservative about words to be robust against string concatenation. But we don't do anything like that, so we can be much more aggressive.
=> Form purify-css and make it work much better.

contents/js/main.js
See https://www.webpagetest.org/result/180429_NT_7f216116f935696ea062d6b11bd1569a/3/details/#waterfall_view_step1
=> Check if this helps with the weird late renders

config.json, contents/css/_sponsor.css, scripts/spreadsheet-import/index.js, templates/filters/simplifiedUrl.js, templates/pages/sponsor.html.njk, templates/pages/sponsors.html.njk
=> Sponsor detail pages

contents/schedule-venue.json, templates/pages/schedule-venue.html.njk
This runs during breaks and one displays throughout the venue.
=> Generate schedule for use during the event.

contents/copy/scholarships/guide.md
this is almost the same content as the cssconf version, as we have mostly combo tickets
=> add jsconf scholarship guide

contents/copy/speakers/guide.md
@janl & @simonehaas 
I copied the speakers guide from cssconf. can you both have a look at the content? thank you :)
#148
=> add speakers guide

templates/pages/schedule.html.njk
…and actually make the adding of `.in-the-past` work.
Add `#cycle` to URL to activate cycling through time.
=> Add support for virtually cycling time to schedule

contents/news/conference-menu.md
rename indian / asian names for dishes; make more clear what's a kid's menu; consistency issues
=> proofread menu

contents/copy/coc/code-of-conduct.md
=> Adjust the Code of Conduct

templates/pages/index.html.njk
=> Changing the text, so I don't have to change the CSS.

.travis.yml
It broke twice in the last 2 days.
=> Turn off travis caching.

templates/pages/schedule.html.njk
Date.parse isn’t working in Safari so do a Stackoverflow thing
=> Fixes scroll to talk on iOS

contents/copy/privacy-policy/privacy-policy.md
I found a typo ... while I was copying parts of your awesome gdpr for our own conference 🤫
=> fix(privacy-policy): fix typo
