- index.html
The current layout on smaller screens might give a false impression of missing content.
LEFT: NEW – RIGHT: BEFORE
> Add minor layout improvements

- contents/index.json
- package-lock.json
- templates/layouts/default.html.njk
I couldn't test this yet, because `npm i` does not successfully terminate on the plane.
- Make TypeKit not block page display.
- Preconnect to TypeKit's font origin concurrently with JS download..
- Start download of JS file earlier.
- Moved SVG sprite to the end to put main content ahead in the stream.
- Use `title` instead of `name` for page title. Matches what is actually specified in JSON files.
- Switch the `meta-description` to be page based instead of site based and only print it if defined.
- Fixed a broken link to ti.to.
- Fixed homepage title
> A few drive-by performance and SEO fixes.

- contents/copy/scholarships/scholarships.md
Apparently we show a wrong email address [on the Scholarships page](https://2018.jsconf.eu/scholarships/). ;(
> Fix email address on the Scholarships page

- contents/css/_layout.css
As discussed with @silkine: Ornaments are now hidden on smaller screens.
> hide ornaments on smaller screens

- CODE_OF_CONDUCT.md
the website team wants to open the project for contributors. these code of conduct should should help to clarify that contributing is only possible with accepting the code of conduct.
****
fix issue: #52
I will copy these to cssconf as soon as it's approved
> issue #52 - code of conduct for contributing

- contents/css/_links.css
- templates/pages/call-for-speakers.html.njk
- templates/pages/code-of-conduct.html.njk
- templates/pages/imprint.html.njk
- templates/pages/scholarships.html.njk
- templates/pages/sponsors.html.njk
- templates/pages/time.html.njk
Due to a oversight on my part in #56, a too broad selector (`.main-wrapper a`) for the underlined links leads to problems with the `.btn` buttons, which can be `.main-wrapper a` as well.
Understanding that the `.main-wrapper a` selector was used to also affect all links coming from markdown content, I added a new class `.md-content` on all elements containing content from markdown so we can target that instead.
An alternative option would be to only target links with no further class (`.main-wrapper a:not([class])`).
wdyt?
> Fix button-breakage from #56

- templates/pages/index.html.njk
Added the copy (as agreed with Mercedes-Benz.io, this needs to go live before end of year).
The layout is not ideal yet for longer copy like this. This will be addressed in https://github.com/jsconf/2018.jsconf.eu/issues/47
/cc @lukaszklis @silkine
> Add announcement post for Mercedes-Benz.io sponsorship

- contents/news.json
- contents/news/news-template.md
- templates/pages/news-item.html.njk
- templates/pages/news.html.njk
My first attempt to bring the News section to JSConf EU.
Here’s the structure we should follow:
1. We add new News item as a Markdown file under `contents/news` (see `news-template.md` as a reference).
1. You can use a draft by setting the ”draft” metadata in the news item’s formatter. All of the News items with this metadata would not be shown on the News list (however they would still be accessible via the news item details link)
1. List of news can be accessed at `/news/`.
1. A specific news item can be accessed at `/news/news-title/`
You can see a preview here: https://user-images.githubusercontent.com/11782/34304446-1a01e274-e73a-11e7-871b-d429d972f588.png
> Add the news section

- contents/news/mercedes-benz-supports-scholarship-program.md
- templates/pages/index.html.njk
- templates/partials/topbar.html.njk
Credits to @lukaszklis for introducing the news section in #62 and to @kriesse for providing the content in #64.
This PR moves the MB content into a proper news article and then:
- actually links the news section in the main navigation
- and replaces the MB content on the homepage with automatically a generated snippet of the latest news post.
Does not fix the problem that this doesn't look particularly good yet as #64 mentions :)
> Move MB article to be proper news article and link news on homepage and main nav.

- contents/css/_links.css
- contents/news/mercedes-benz-supports-scholarship-program.md
- plugins/nunjucks.js
- templates/pages/index.html.njk
- templates/pages/news.html.njk
In particular this adds a `notDraft` filter to make templates more concise.
> Correctly style content links on homepage and a few small fixes.

- contents/css/_layout.css
- contents/css/_topbar.css
- contents/css/_typography.css
- package-lock.json
- package.json
- plugins/nunjucks.js
- plugins/postcss.js
- templates/layouts/default.html.njk
I configured cloudflare to assign a 1 year cache time to every resource starting with `immutable/`.
Sorry for the nasty implementation. It would be much nicer if wintersmith has a pipeline of plugins instead of assigning each resource to exactly one of them.
> Convert URLs to static assets into immutable URLs

- scripts/spreadsheet-import/index.js
- templates/pages/speaker.html.njk
- templates/pages/speakers.html.njk
- templates/partials/talk.html.njk
- Adopts templates to actual spreadsheet.
- Makes overview page have all content.
- Changes the import script to emit the title as document meta data.
> Emit all data for speaker pages.

- contents/speakers/ashi-krishnan-deep-learning-in-js.md
- contents/speakers/emil-bay-hand-crafting-webassembly.md
- contents/speakers/shelley-vohr-asynchrony-under-the-hood.md
- scripts/spreadsheet-import/index.js
writing to templateGlobals in an async context lets the last value written 
win, hence the problem with identical titles on all pages yesterday. 
Didn't happen for me as using local files keeps everything running in sync.
Also adds a new frontmatter-variable `name`, which might make sense at some point.
> fix: async race-condition

- package-lock.json
- package.json
- plugins/postcss.js
- scripts/purify-css.js
This roughly cuts the CSS size in half.
Implemented as a script because it has to run post build to be able to see all generated HTML (including from markdown). 
Changed the CSS hashing to include our own CSS code as well as the names and versions of the module dependencies that deal with css. However, now HTML changes can cause less or more CSS to be retained, so we still have to re-hash, rename, and update references post purification.
> Drop unused CSS selectors.

- .travis.yml
The CSS purification is sensitive to having multiple CSS builds lying around.
> Because we build twice, move the non-deploy build out of the way.

- contents/js/main.js
- templates/layouts/default.html.njk
- templates/pages/index.html.njk
- templates/partials/topbar.html.njk
Prefetches the main doc and known sub resources whenever a doc finishes loading.
On mouseover and click of the purchase button, preconnects to ti.to and other origins that ti.to uses to flatten the connection tree.
> ⚡  Optimize the purchase flow by prefetching and preconnecting from/to ti.to

- templates/_macros.njk
- templates/layouts/default.html.njk
- templates/pages/index.html.njk
- templates/partials/talk.html.njk
- templates/partials/topbar.html.njk
This is a better strategy because
- (and this could be fixed differently) we put way too much crap into the sprite
- sprites are the wrong way under H2
I'm still using an inline SVG with `<image>` element (and a preload element for preload scanner support), so that layout remains unchanged.
> Switch to external SVGs

- contents/sw.js
- templates/layouts/default.html.njk
Will get rid of the FOUT.
And updates preloads to current state (switches every 100 days).
> Switch to CSS based typekit loading.

- contents/css/_speaker.css
Sorry, my long last name is breaking the layout.
`word-break: break-word;` should fix this without affecting other pages.
> Fix long speaker names break layout on small devices

- templates/layouts/default.html.njk
Because it interferes with network bound users.
> Don't preload fonts with font-display: optional

- plugins/nunjucks.js
Still in crazy hack territory, but this speed up development, by allowing simple reloads while immutable resources are cached.
> No caching for local html responses

- contents/copy/scholarships/guide.md
- contents/scholarships-guide.json
- templates/pages/scholarships-guide.html.njk
> Add skeleton for the Scholarships Guide page

- contents/css/_links.css
- templates/partials/talk.html.njk
This limits the default-underlining of links to the actual body of the speaker page and avoids a specificity conflict with the buy button.
Fixes #176
> Fix CSS specificity conflict.

- templates/layouts/default.html.njk
It steals bandwidth from high priority resources and leads early rasterization may delay paint.
See https://bugs.chromium.org/p/chromium/issues/detail?id=838396
> Stop preloading the background.

- schedule.json
- templates/pages/schedule.html.njk
- this works on screens wider than 767 px (smaller have the single column view)
- works on Chrome & Firefox (unable to manually check other browsers)
**Screenshot**
> schedule now shows parallel events on one row

- schedule.json
- templates/pages/schedule.html.njk
I don't know why the schedule.json shows as updated, not sure how to exclude it from the PR. 
Gray speaker names and track names are deliberate to avoid block of black. 
**Screenshot
**
> Cleaned up print view
